### ISSUE TITLE
RSS support for the blog

### ISSUE THREAD

**Issue by kuchta** [oxc-project/oxc-project.github.io#104]
Please add RSS/Atom support so we can follow...

**Comment by Boshen** [comment]
We need to add the links somewhere.

* https://oxc-project.github.io/feeds/blog-en.rss
* https://oxc-project.github.io/feeds/blog-en.atom

**Comment by kuchta** [comment]
Cool, thank you @Boshen 🙏🏻. Link the feed into the page, so that RSS readers could auto-discover them:

```
<head>
  <link rel="alternate" type="application/rss+xml" href="https://oxc-project.github.io/feeds/blog-en.atom">
</head>
```

**Comment by gBasil** [comment]
@kuchta That's already implemented, there just isn't a direct, user-visible link on the page, which is what Boshen is referring to.

**Comment by kuchta** [comment]
@gBasil Is it really needed? Users of RSS are probably used to using just the page URLs, since less than 10% of the pages with RSS have it user-visible somewhere on the page...

**Comment by kuchta** [comment]
@Boshen JFYI, that title attribute gets ignored by my reader, so it looks like this:

<img width="480" alt="image" src="https://github.com/oxc-project/oxc-project.github.io/assets/903277/643984cc-413d-4d14-a830-b2f4d5a7d056">

**Comment by gBasil** [comment]
> @gBasil Is it really needed? Users of RSS are probably used to using just the page URLs, since less than 10% of the pages with RSS have it user-visible somewhere on the page...

I have no idea, I'm not all that knowledgable in the RSS/Atom space.

**Comment by Boshen** [comment]
Oh cool, I installed a Chrome RSS extension and confirmed everything is working as intended. A dedicated button is not needed. Thank you all for testing!
