### ISSUE TITLE
【bug】The official website cannot be opened

### ISSUE THREAD

**Issue by baiwusanyu-c** [oxc-project/oxc-project.github.io#119]
![image](https://github.com/oxc-project/oxc-project.github.io/assets/32354856/1ea520a8-227d-40d8-9f34-dd2546a73df4)

**Comment by baiwusanyu-c** [comment]
![image](https://github.com/oxc-project/oxc-project.github.io/assets/32354856/3e3ad7a5-7c50-4fc1-8b62-3843083ea0fc)

**Comment by Boshen** [comment]
Ahh we are trying to setup a domain for the website, but dns propagation seems to be broken or slow ...

I reverted the domain update, you may need a hard refresh to visit https://oxc-project.github.io
