### ISSUE TITLE
Add more features

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc-project.github.io#3]
Continue on https://github.com/oxc-project/oxc-project.github.io/pull/1:

VitePress has some features that you might get interested in:

- [x] [Local search](https://vitepress.dev/reference/default-theme-search)
- [x] [Team page](https://vitepress.dev/reference/default-theme-team-page)
- [ ] [Badge](https://vitepress.dev/reference/default-theme-badge)
- [ ] [Carbon ads](https://vitepress.dev/reference/default-theme-carbon-ads)

**Comment by NozomuIkuta** [comment]
Local search is already enabled.
Press Cmd+K in any page and you can use it.

**Comment by NozomuIkuta** [comment]
Team page feature has been published as a part of #16
