### ISSUE TITLE
Persist removal of banner of closing it

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxc-project.github.io#74]
The close button doesn't persist after browser refresh :-(

**Comment by Dunqing** [comment]
Do we need to set a closing period(1d or 7d) to avoid being unable to see the next banner?

**Comment by Boshen** [comment]
> Do we need to set a closing period(1d or 7d) to avoid being unable to see the next banner?

We can add a ID to the banner.

**Comment by Boshen** [comment]
Can we also hide the banner on the announcement blog page? Sorry I'm really bad at web development :-/

**Comment by Dunqing** [comment]
> Can we also hide the banner on the announcement blog page? Sorry I'm really bad at web development :-/

Yes, we can
